CREATE TABLE PATIENTS(
    USERNAME            VARCHAR2(255) NOT NULL,
    NAME                VARCHAR2(255),
    ADDRESS             VARCHAR2(255),
    EMAIL               VARCHAR2(255) NOT NULL,
    MEDS                VARCHAR2(255),
    LASTATTEND          VARCHAR2(255),
    PRIMARY KEY(USERNAME, EMAIL)
);

CREATE TABLE Appointments(
    PATIENTUNAME        VARCHAR2(255) NOT NULL,
    PATIENTFNAME        VARCHAR2(255),
    PATIENTLNAME        VARCHAR2(255),
    PATIENTEMAIL        VARCHAR2(255) NOT NULL,
    PATIENTATTEND       VARCHAR2(255),
    PATIENTMEDS         VARCHAR2(255),
    APPOINTMENTDATE     VARCHAR2(255) NOT NULL,
    APPOINTMENTTIME     VARCHAR2(255) NOT NULL,
    PRIMARY KEY (PATIENTUNAME, PATIENTEMAIL, APPOINTMENTDATE, APPOINTMENTTIME)
    );
